### ISSUE TITLE
Text file busy error

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-filter_wiris#1]
During a Moodle quiz, we experienced the follow message.  Is this an issue with how the filter works, or is it a server configuration issue?

![error](https://cloud.githubusercontent.com/assets/989354/15015937/a18edd94-11dc-11e6-99cc-e48851f30219.jpg)

**Comment by wirismath** [comment]
Does this happen all the time or did you just experiece this issue on one particular attempt?
Thanks!
*Lidia (WIRIS support)

**Comment by Syxton** [comment]
As far as I know it has only happened once, but I thought I'd report it anyway.

**Comment by wirismath** [comment]
Thank you! We will investigate further on our end.
