### ISSUE TITLE
EN_US

### ISSUE THREAD

**Issue by dbnschools** [wiris/moodle-filter_wiris#12]
We are having an issue when using English US as the default language for Moodle.  It breaks the buttons in the atto editor.  We get a 404 error in the browser for the language string.  Editor/atto/plugins/wiris/lang/en_us is missing.  I copied the en folder and made it en_us and the editor started working again.

**Comment by manuelwiris** [comment]
Hi @dbnschools  

Thanks for your feedback. 

The issue is fixed with our las release #14 

Best, regards
