### ISSUE TITLE
uncaught exception: Creation of dynamic property filter_wiris_pluginwrapper::$moodleConfig is deprecated (errno: 8192) 

### ISSUE THREAD

**Issue by prcctv** [wiris/moodle-filter_wiris#123]
Moodle version: Moodle 4.2
PHP Version: 8.2.5
Plugin ID: filter_wiris
Plugin version: 8.2.6 (2023042400)

Problem
After upgrading the PHP on our server to version 8.2.5, the "Site administration" main page is unreachable, and also the at least the "Plugins overview" page. Instead of the page itself, we see the following message:

uncaught exception: Creation of dynamic property filter_wiris_pluginwrapper::$moodleConfig is deprecated (errno: 8192) in /var/www/html/moodle/filter/wiris/classes/pluginwrapper.php at line #85Creation of dynamic property filter_wiris_pluginwrapper::$moodleConfig is deprecated

in file: /var/www/html/moodle/filter/wiris/classes/pluginwrapper.php line 85
#0 /var/www/html/moodle/filter/wiris/classes/pluginwrapper.php(85): _hx_error_handler()
#1 /var/www/html/moodle/filter/wiris/classes/pluginwrapper.php(54): filter_wiris_pluginwrapper->init()
#2 /var/www/html/moodle/filter/wiris/settings.php(35): filter_wiris_pluginwrapper->__construct()
#3 /var/www/html/moodle/lib/classes/plugininfo/filter.php(138): include('...')
#4 /var/www/html/moodle/admin/settings/plugins.php(273): core\plugininfo\filter->load_settings()
#5 /var/www/html/moodle/lib/adminlib.php(8709): require('...')
#6 /var/www/html/moodle/admin/index.php(842): admin_get_root()
#7 {main}

**Comment by carla-at-wiris** [comment]
Hello @prcctv, thank you for reaching us regarding this matter.

Currently, Moodle is not even compatible with PHP 8.2 or higher, but it's under development, as you can see on [this page](https://moodledev.io/general/development/policies/php#:~:text=PHP%208.0%20can%20be%20used,supported%20version%20for%20Moodle%204.2.).

We will follow their development and start working on the compatibility as soon as possible. In the meantime, you can check the status of the Moodle compatibility with PHP 8.2 [here](https://tracker.moodle.org/browse/MDL-76405).

We will proceed to close this issue. Please, feel free to reopen it if, after Moodle's official compatibility release with PHP 8.2, you find that the issue persists.

**Comment by prcctv** [comment]
> Hello @prcctv, thank you for reaching us regarding this matter.
> 
> Currently, Moodle is not even compatible with PHP 8.2 or higher, but it's under development, as you can see on [this page](https://moodledev.io/general/development/policies/php#:~:text=PHP%208.0%20can%20be%20used,supported%20version%20for%20Moodle%204.2.).
> 
> We will follow their development and start working on the compatibility as soon as possible. In the meantime, you can check the status of the Moodle compatibility with PHP 8.2 [here](https://tracker.moodle.org/browse/MDL-76405).
> 
> We will proceed to close this issue. Please, feel free to reopen it if, after Moodle's official compatibility release with PHP 8.2, you find that the issue persists.

Hi，Carla，IC, Thank you for response.
