### ISSUE TITLE
Quiz preview broken when using Wiris Cloze

### ISSUE THREAD

**Issue by kiratskitizing** [wiris/moodle-filter_wiris#134]
Quiz preview broken and showing wiris stacktrace.

1. Create a course.
2. Turn edit mode to On.
3. Add a quiz.
4. Go to the quiz and add question:
Select WIRIS QUIZZES -Cloze Science
name: my Wiris Q
question text (copy and paste to editor): test123 {1:SA:=#m1100000000} {1:MCS:=#SG11#SG12~#SG13~#SG14}
«math xmlns=¨http://www.w3.org/1998/Math/MathML¨»«mo»§#8943;«/mo»«/math»
5. Click "Decode and verify the question text" and save it.
6. Click the Quiz tab.
7. Click Preview quiz button.
8. Do not do anything.
9. Click the Questions tab 
10. Click the bottom "Add" > Select Description.
name: description
text: (copy and paste to editor): test123 {1:SA:=#m1100000000} {1:MCS:=#SG11#SG12~#SG13~#SG14}
«math xmlns=¨http://www.w3.org/1998/Math/MathML¨»«mo»§#8943;«/mo»«/math»
11. Save changes.
12. Click the "move" icon of the description you have just added and select "After page1".
13. Click on the Quiz tab.
14. Click Preview quiz

RESULT:
you will get the error below:
```
Exception - Undefined property: _hx_array::$a (errno: 2) in [dirroot]/filter/wiris/integration/lib/php/Lib.class.php at line #31

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 49 of /question/type/wq/quizzes/lib/com/wiris/quizzes/wrap/QuestionWrap.class.php: HException thrown
    line 264 of /question/type/shortanswerwiris/question.php: call to com_wiris_quizzes_wrap_QuestionWrap->getSlots()
    line 254 of /question/type/shortanswerwiris/question.php: call to qtype_shortanswerwiris_question->is_text_answer()
    line 322 of /question/type/shortanswerwiris/question.php: call to qtype_shortanswerwiris_question->format_answer()
    line 93 of /question/type/multianswerwiris/renderer.php: call to qtype_shortanswerwiris_question->get_correct_response()
    line 199 of /question/type/multianswerwiris/renderer.php: call to qtype_multianswerwiris_shortanswer_helper_question->get_correct_response()
    line 32 of /question/type/multianswerwiris/renderer.php: call to qtype_multianswerwiris_wirisanswerfield_renderer->subquestion()
    line 71 of /question/type/multianswer/renderer.php: call to qtype_multianswerwiris_helper_renderer->subquestion()
    line 30 of /question/type/wq/renderer.php: call to qtype_multianswer_renderer->formulation_and_controls()
    line 403 of /question/engine/renderer.php: call to qtype_wq_renderer->formulation_and_controls()
    line 108 of /question/engine/renderer.php: call to core_question_renderer->formulation()
    line 113 of /question/behaviour/behaviourbase.php: call to core_question_renderer->question()
    line 907 of /question/engine/questionattempt.php: call to question_behaviour->render()
    line 461 of /question/engine/questionusage.php: call to question_attempt->render()
    line 1783 of /mod/quiz/attemptlib.php: call to question_usage_by_activity->render_question()
    line 1745 of /mod/quiz/attemptlib.php: call to quiz_attempt->render_question_helper()
    line 521 of /mod/quiz/renderer.php: call to quiz_attempt->render_question()
    line 459 of /mod/quiz/renderer.php: call to mod_quiz_renderer->attempt_form()
    line 139 of /mod/quiz/attempt.php: call to mod_quiz_renderer->attempt_page()
```
    
    
You will never be able to preview the quiz again.

**Comment by icaparros-at-wiris** [comment]
Hello @kiratskitizing.

First of all, thank you for reporting the issue! This bug will be fixed in the next release in the second half of November.

Thank you :)

**Comment by carla-at-wiris** [comment]
Hi @kiratskitizing!

Thank you for writing us. Since the fix release has already been done, we will be closing this issue.

If you need further assistance here, feel free to reopen this issue or contact us at [support@wiris.com](mailto:support@wiris.com).
