### ISSUE TITLE
mdl4.1 syntax error

### ISSUE THREAD

**Issue by MURBASLMS** [wiris/moodle-filter_wiris#138]
Parse error: syntax error, unexpected '$', expecting '|' or variable (T_VARIABLE) in ./filter/wiris/integration/lib/com/wiris/plugin/impl/RenderImplIntegratedServices.class.php on line 32
Errors parsing ./filter/wiris/integration/lib/com/wiris/plugin/impl/RenderImplIntegratedServices.class.php
xargs: php: exited with status 255; aborting

cheers

**Comment by carla-at-wiris** [comment]
Hi @MURBASLMS, thank you for noticing this!

We will send the issue to development and let you know once the fix is released. If you experience any further issues, please feel free to contact us!

**Comment by carla-at-wiris** [comment]
Hello @MURBASLMS,

Our version `8.6.3` contained a solution for this issue. Our latest one is the `8.7.0` which also includes compatibility with Moodle 4.4. Any further issues, please let us know!
