### ISSUE TITLE
not UTF8 files and strange characters

### ISSUE THREAD

**Issue by birdy4012** [wiris/moodle-filter_wiris#15]
hi,
in integration/lib, a lot of files aren't in UTF8, and have strange characters.
Exemple in integration/lib/Hash.class.php: 
line 14:
```
$»it = $it;
while($»it->hasNext()) {
```
line 57:  `else if(isset($this->»dynamics[$m]) && is_callable($this->»dynamics[$m]))`

Is it correct ?

**Comment by manuelwiris** [comment]
@birdy4012 

This character belongs to PHP API. It's referred as an external library in Moodle. It's correct.

Best regards,
