### ISSUE TITLE
Issue trying to save a quizz with WIRIS answers

### ISSUE THREAD

**Issue by gonzalolarralde** [wiris/moodle-filter_wiris#18]
Hi,

We have a moddle installation with the WIRIS plugin integrated. When we are resolving a quizz, the WIRIS editor is working properly in the quizz editor, but when we try to save the response (processattempt) we're getting the following error:

Unknown driver native/mysql

Needless to say that this is a moodle already in production and that all other plugins are working and therefore getting the database driver / properties properly, so in this case this is the only plugin showing up this error. All the responses I could find to this scenario talks about a global issue vs a particular one.

Sorry for not providing more details, I'm not the administrator of the platform but trying to find a lead to help them figure out the issue so we can use this amazing plugin. Is there anything that you think may be affecting the DBconfig only for the WIRIS plugin?

Thank you!

**Comment by manuelwiris** [comment]
Hi @gonzalolarralde 

I think there's nothing in DBconfig affecting only WIRIS Plugin. However it would be helpful if you can provide us more specific details about your sever configuration?
