### ISSUE TITLE
Unable to save questions and answers containing Wiris Equations in PDF

### ISSUE THREAD

**Issue by ajinkyagadewar** [wiris/moodle-filter_wiris#19]
Hello:

We have saved equations in MathML format. It works fine for HTML viewing but when to try to save in PDF nothing is getting displayed.

What can be the issue?

**Comment by manuelwiris** [comment]
@ajinkyagadewar 

Can you provide us more details about your issue? What kind of activity are you trying to save in PDF? 

Best,

**Comment by ajinkyagadewar** [comment]
Hello Manuel:

Following is the text I am trying to put in PDF.

![screen shot 2017-10-02 at 7 55 18 pm](https://user-images.githubusercontent.com/3275617/31082135-b3c51724-a7ab-11e7-9f8a-0d75f594eacb.png)

**Comment by ajinkyagadewar** [comment]
You need more information on this?
