### ISSUE TITLE
Undefined variable: carry

### ISSUE THREAD

**Issue by sarjona** [wiris/moodle-filter_wiris#3]
La versió nova del filtre de wiris té el warning següent (perquè fa referència a una variable que no està declarada enlloc):

` Notice: Undefined variable: carry in /dades/agora/html/moodle2/filter/wiris/lib.php on line 125
`

**Comment by sarjona** [comment]
La versió nova del filtre (publicada el passat 5 de gener de 2017) encara conté el mateix error :-(

**Comment by manuelwiris** [comment]
Sara, la nueva versión (4.1.0) ya corrige este error. 

Un saludo,

**Comment by sarjona** [comment]
Excelente noticia!! :-)
