### ISSUE TITLE
Random error that shows up

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-filter_wiris#4]
I have a simple equation in a course label.  Sometimes I get the following error and sometimes it works as expected.

uncaught exception: fopen(/var/www/moodledata/SharedCache/cachestore_file/default_application/core_databasemeta/bbf-cache/bbf213178611dfbe0e377620f6d0b86824991516.cache): failed to open stream: No such file or directory (errno: 2) in /var/www/moodle/cache/stores/file/lib.php at line #358fopen(/var/www/moodledata/SharedCache/cachestore_file/default_application/core_databasemeta/bbf-cache/bbf213178611dfbe0e377620f6d0b86824991516.cache): failed to open stream: No such file or directory

in file: /var/www/moodle/cache/stores/file/lib.php line 358
#0 [internal function]: _hx_error_handler(2, 'fopen(/var/www/...', '/var/www/moodle...', 358, Array)
#1 /var/www/moodle/cache/stores/file/lib.php(358): fopen('/var/www/moodle...', 'rb')
#2 /var/www/moodle/cache/classes/loaders.php(303): cachestore_file->get('bbf213178611dfb...')
#3 /var/www/moodle/cache/classes/loaders.php(1461): cache->get('filter_active', 0)
#4 /var/www/moodle/lib/dml/mysqli_native_moodle_database.php(585): cache_application->get('filter_active')
#5 /var/www/moodle/lib/dml/moodle_database.php(618): mysqli_native_moodle_database->get_columns('filter_active')
#6 /var/www/moodle/lib/dml/moodle_database.php(1306): moodle_database->where_clause('filter_active', Array)
#7 /var/www/moodle/lib/filterlib.php(1100): moodle_database->get_records('filter_active', Array, 'sortorder', 'filter,active,s...')
#8 /var/www/moodle/lib/filterlib.php(686): filter_get_global_states()
#9 /var/www/moodle/filter/wiris/classes/configurationupdater.php(62): filter_get_globally_enabled()
#10 /var/www/moodle/filter/wiris/classes/configurationupdater.php(97): filter_wiris_configurationupdater->get_latex_status()
#11 /var/www/moodle/filter/wiris/integration/lib/com/wiris/plugin/impl/ConfigurationImpl.class.php(151): filter_wiris_configurationupdater->updateConfiguration(Array)
#12 /var/www/moodle/filter/wiris/integration/lib/com/wiris/plugin/impl/ConfigurationImpl.class.php(162): com_wiris_plugin_impl_ConfigurationImpl->initialize0()
#13 /var/www/moodle/filter/wiris/integration/lib/com/wiris/plugin/impl/TextFilter.class.php(151): com_wiris_plugin_impl_ConfigurationImpl->getProperty('wiriseditormath...', 'data-mathml')
#14 /var/www/moodle/filter/wiris/integration/lib/com/wiris/plugin/impl/TextFilter.class.php(218): com_wiris_plugin_impl_TextFilter->filterMath(Object(com_wiris_plugin_impl_TextFilterTags), '
filter('
apply_filter_chain('

**Comment by manuelwiris** [comment]
Hi Syxton, 

Seems we are handling Moodle warnings as an exception, we'll try to fix it in our March release.

Thanks for your feedback,

**Comment by manuelwiris** [comment]
Hi Syxton, 

The new version (4.1.0) fix this bug. 

Thanks,
