### ISSUE TITLE
Wiris-filter disables filepicker on IE11

### ISSUE THREAD

**Issue by Jarvil** [wiris/moodle-filter_wiris#45]
Hello,

If I have filter_wiris 7.12.0.1412 (2019040800) enabled on a course on Moodle 3.5.5 I cannot add any files to f.ex. assignment additional files field or Course summary files with Internet Explorer 11, it just loads forever. 

So the wiris filter disables filepicker in certain fields with IE11. Seems like a pretty bad bug. @manuelwiris 

With another browser like Chrome filepicker works wiris filter enabled on a course.

**Comment by raul-at-wiris** [comment]
Hello,

We could not reproduce the issue on Moodle 3.5.5 and IE11.

A filepicker that does not load in Moodle usually indicates some issue with JavaScript. We've seen a similar behaviour when the Atto editor from the previous field has issues in the toolbar.

Try setting atto_collapse | showgroups to a lower value (i.e. less than the actual number of rows in editor_atto | toolbar).

If that does not fix the issue, please write to support@wiris.com so we can sort it out.
