### ISSUE TITLE
Wiris doesn't change safeXml content back to normal XML on Solaris because of using non-Multibyte stripos function

### ISSUE THREAD

**Issue by danowar2k** [wiris/moodle-filter_wiris#52]
Hello,

Wiris filters the input by checking for unicode char « in the string. stripos is used, which is non-multibyte. Which doesn't matter on many Linux systems. stripos makes lower case chars out of the haystack, but just ignores the Multibyte chars (doesn't change them, not even to lower case versions).

But on Solaris, rather on PHP 7.1.x (PHP 5.6.x worked), when you have a string like this: "uPPerCase«math[...]", Solaris changes to lowercase and can't find the needle anymore.

Easy solution: Just search for multibyte needles using mb_stripos.

Pull request follows.

**Comment by manuelwiris** [comment]
HI @danowar2k 

Thanks for finding the issue and the PR. We will review the pull request this month. I think we can integrate it during this sprint.

I create a new branch, PLUGINS-1255 to integrate the changes you made #53 

I'll keep the issue open since we integrate the changes.

Thanks,

**Comment by danowar2k** [comment]
Shouldn't this ticket be closed, then?

**Comment by dcanetma** [comment]
You're right, @danowar2k 
Changes are already merged #53 
 
Thanks for mentioning it.

I'm proceeding to close the issue, then.
