### ISSUE TITLE
Update error "Index filter_wiris_formulas->md5 does not exist"

### ISSUE THREAD

**Issue by feupegro** [wiris/moodle-filter_wiris#56]
Hi,

i got an error during updating Wiris Version 2017040600 (4.2.0.1364) to 2019071200 (7.15.0) with Moodle Version: 3.2.7 (Build: 20180115)

**Error:**
``Debug info: Index filter_wiris_formulas->md5 does not exist. Drop skipped
Error code: ddlunknownerror 
Stack trace: 
•	line 857 of /lib/ddl/database_manager.php: ddl_exception thrown
•	line 96 of /filter/wiris/db/upgrade.php: call to database_manager->drop_index()
•	line 558 of /lib/upgradelib.php: call to xmldb_filter_wiris_upgrade()
•	line 1748 of /lib/upgradelib.php: call to upgrade_plugins()
•	line 693 of /admin/index.php: call to upgrade_noncore()``

Commenting out line 96 from upgrade.php
--> //$dbman->drop_index($table, $index);
fixes the error for me.

**Comment by carlawiris** [comment]
Hi, thanks for reporting the issue and sorry for the late response.

This issue is not a problem anymore but many thanks for reporting a solution anyway. If you are still experimenting the error please feel free to open a new issue and we will work on it.
