### ISSUE TITLE
unique key too large if using utf8mb4 encoding (or any 4 byte collation)

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-filter_wiris#6]
Moodle will begin to recommend utf8mb4 in upcoming versions.  https://tracker.moodle.org/browse/MDL-54901

I've recently attempted to install WIRIS on a new 3.3 running with utf8mb4 collation.  It will not install because of the md5 unique key being too many bytes.  Keys have a maximum of 191 characters, or 764 bytes.

**Comment by manuelwiris** [comment]
Hi @Syxton we are aware about this issue with utf8mb4 collation, it will be fixed in our June release. 

Thanks for your feedback

**Comment by manuelwiris** [comment]
@Syxton 

Could you provide us some information about your environment?  Are you using mysql? what version? 

We attempt to install WIRIS on a new 3.3 with utf8mb4 collation and the installation is OK.

IWe change the key length from  255 to 128 (is a md5 so there is not need for a varchar(255) but it would be very helpful if we can reproduce this issue in our environment. 

Thanks in advance,

**Comment by Syxton** [comment]
We are running mysql 5.0.12

**Comment by manuelwiris** [comment]
@Syxton This issue is solved in our last release (4.3.0).

Best regards,
