### ISSUE TITLE
"Not equal to" symbol displaying as a hyphen in demos on IE edge

### ISSUE THREAD

**Issue by timothyfisherdev** [wiris/moodle-filter_wiris#62]
I've noticed that the "not equal to" symbol is displaying as a hyphen, but only in IE edge. See the PHP integration demo here for example: http://www.wiris.com/plugins/demo/tinymce4/php/.

To reproduce, in IE edge click the "Insert special characters" button, then search for "8800" or select the "not equal to" characer. It shows correctly in the editor, however, once you click "Ok" the symbol shows up as a hyphen (see below):

<img width="369" alt="Screen Shot 2019-12-03 at 11 18 32 AM" src="https://user-images.githubusercontent.com/38889944/70077962-1399ba00-15bf-11ea-95bd-341e51ee7a93.png">

This happens with any of the integration demos and only in IE edge. I'm assuming it has to do with this specific package, but I could be wrong.

Any idea what is causing this?

**Comment by timothyfisherdev** [comment]
After poking around a little bit more, I found that the symbol was being included in the SVG in a `<text>` tag with the font family set to the generated MathML font, like this:

`<text font-family="math1e73b84a23c3d1c1163dfc45bd2" font-size="16" text-anchor="middle" x="55.5" y="45">&#x2260;</text>`

Changing that font-family attribute back to Arial fixed it. Must be something wrong with edge rendering fonts in SVGs?

**Comment by carlawiris** [comment]
Hi, thanks for the report and sorry for the delay in response.

Currently this issue has not been able to reproduce in the conditions mentioned and with the latest versions of the plugin, so we can say that this problem has been solved and does not happen if you use the latest version of the plugin.
