### ISSUE TITLE
"Passing glue string after array is deprecated" - error under PHP 7.4

### ISSUE THREAD

**Issue by phinor** [wiris/moodle-filter_wiris#63]
In PHP 7.4, the ability to pass the glue string after the array has been [deprecated](https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix) for the `implode` function and its `join` alias.

In the `filter/wiris/integration/lib/php/Boot.class.php` file, there are two occurrences of the `join` functions on lines 834 and 840 are two occurrences of this function with the incorrect parameter order which results in the script crashing.

I have not checked other files for use of the `join` function.

**Comment by WNYmathGuy** [comment]
I'm also having this error. Logged in as admin and trying to go to the admin page I get this:

```
uncaught exception: join(): Passing glue string after array is deprecated. Swap the parameters (errno: 8192) in /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/integration/lib/php/Boot.class.php at line #834join(): Passing glue string after array is deprecated. Swap the parameters

in file: /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/integration/lib/php/Boot.class.php line 834
#0 [internal function]: _hx_error_handler()
#1 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/integration/lib/php/Boot.class.php(834): join()
#2 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/integration/lib/php/Boot.class.php(853): _hx_build_paths()
#3 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/integration/lib/com/wiris/system/CallWrapper.class.php(44): require_once('/home/outmathad...')
#4 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/classes/pluginwrapper.php(80): com_wiris_system_CallWrapper->init()
#5 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/classes/pluginwrapper.php(54): filter_wiris_pluginwrapper->init()
#6 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/filter/wiris/settings.php(35): filter_wiris_pluginwrapper->__construct()
#7 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/lib/classes/plugininfo/filter.php(88): include('/home/outmathad...')
#8 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/admin/settings/plugins.php(223): core\plugininfo\filter->load_settings()
#9 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/lib/adminlib.php(8385): require('/home/outmathad...')
#10 /home/outmathadmin/domains/learn.outsourcedmath.com/public_html/moodle/admin/search.php(26): admin_get_root()
#11 {main}
```

I would guarantee this is a problem related to PHP 7.4.4 because I never had this problem before and yesterday I decided to remove the PHP 7.3 from my base server and only have one choice for PHP on it. Today I discovered the new problem. If I hide the `~moodle/filter/wiris` folder the system acts normal but of course wines about the missing WIRIS Math Type Filter.

**Comment by WNYmathGuy** [comment]
> I would guarantee this is a problem related to PHP 7.4.4 because I never had this problem before and yesterday I decided to remove the PHP 7.3 from my base server and only have one choice for PHP on it. 

_Whoever said that needs to learn the difference between correlation and causation._ "**guarantee**" :roll_eyes: 

I put the PHP 7.3 back on my system and then had the virtual server with the Moodle switch over to using the last version of PHP and the problem persists. I'm stuck in a loop of unserviceability. I don't know the command line things to remove plugins and alter the database. 

This problem has happened before based on the **Comments** section of the plug-in page https://moodle.org/plugins/filter_wiris

**Comment by WNYmathGuy** [comment]
I found a solution while perusing on https://moodle.org/mod/forum/discuss.php?d=400680 and saw Ken Task talk about the programs in the `~/admin/cli` directory of the Moodle sites base folder.

I have shell prompt command access to my server, so if you don't have that, the rest of what I write is moot. 

After I changed into the websites root directory (_where I run_ `git pull` _commands, which for most people is the folder named_ `moodle`), I then navigate two directories deeper to `~moodle/admin/cli` with the `cd admin/cli` command. 
In that directory, I can see all the operations I can run by executing the `ls -A` command.  The only one I needed to get out of this jam was `uninstall_plugins.php`, well, _that and to remove the folders of the plugins too_. 
The `php uninstall_plugins.php` command only removes the tables from the database. If you only run that command and reopen your site as the admin, it will force the reinstalling of the databases to match the installed plugins based on the moodle system folder's contents. I had to both remove the problem addon folder and run the PHP command. 

I have a point & click interface to manage the base server to do things like deleting folders, but here's a set of all shell commands to get out of the **WIRIS MathType** trouble. 
(_Note: I had linked dependencies to the Filter WIRIS, so I removed them first_)
(_Also Note: `php uninstall_plugins.php -h` will explain tips and tricks for using the `uninstall_plugins.php` command_)
- `php uninstall_plugins.php --plugins=editor_tinymce --run` 
- `php uninstall_plugins.php --plugins=editor_atto --run` 
- `php uninstall_plugins.php --plugins=filter_wiris --run` 
- `cd ../../lib/editor` (_up two directories and down two_) 
- `rm atto` (_Remove the object named atto_)
- `rm tinymce` 
- `cd ../../filter` 
- `rm wiris` 

That should work for the general case, barring typos, or minor system differences. After navigating into a directory you can check the actual folder names by executing a `ls -alS` command and you'll see all the directories listed at the top.

**Comment by nadavkav** [comment]
I also am experiencing this while upgrading to Moodle 3.9 using PHP 7.4

**Comment by WNYmathGuy** [comment]
> I also am experiencing this while upgrading to Moodle 3.9 using PHP 7.4
> 
> UPDATE: After installing and switching to php-fpm 7.2 ... everything works fine.

I'm glad I couldn't update to 3.9 yet. I almost did but it's requiring a version of MariaDB that Ubuntu didn't put in their repository yet.

**Comment by carlawiris** [comment]
Hi, thanks for the report and sorry for the delay in responding.

As we assume you have already seen, this issue is not reproduced in the latest version of moodle-filter_wiris, the 7.24.0 released on September 3rd, that is, it is already solved.
You can download the latest version and work without the problem mentioned.

**Comment by WNYmathGuy** [comment]
> Hi, thanks for the report and sorry for the delay in responding.
> 
> As we assume you have already seen, this issue is not reproduced in the latest version of moodle-filter_wiris, the 7.24.0 released on September 3rd, that is, it is already solved.
> You can download the latest version and work without the problem mentioned.

I wound up doing the major upgrades from the Ubuntu approved repositories to the MariaDB and MySQL direct latest stable repositories.

**Comment by Kuldeepguptasrr** [comment]
Replace this file's line with
  "integration/lib/php/Boot.class.php"

$qname = ($bn == 'HList' && empty($pack)) ? 'List' : join(array_merge($pack, array($bn)), '.');  to $qname = ($bn == 'HList' && empty($pack)) ? 'List' : join('.', array_merge($pack, array($bn)));
And 
'phpname' => join(array_merge($pack, array($prefix . $bn)), '_')  to  'phpname' => join('_',array_merge($pack, array($prefix . $bn)))
