### ISSUE TITLE
Array and string offset deprecated on PHP 7.4

### ISSUE THREAD

**Issue by techsupportstaff** [wiris/moodle-filter_wiris#66]
When testing on a machine with PHP 7.4.3 I receive the message:

Array and string offset access syntax with curly braces is deprecated in /data/mdl38/www/filter/wiris/integration/lib/php/Boot.class.php on line 221

**Comment by xaviripo** [comment]
Hi, and sorry for taking so long to respond.

This issue should have been solved in the [7.24.0 release of the MathType filter](https://moodle.org/plugins/pluginversion.php?id=22405). Please inform us if the issue persists after updating,
