### ISSUE TITLE
Unit test failure - test_filter_safexml_with_performance_svg

### ISSUE THREAD

**Issue by kristian-94** [wiris/moodle-filter_wiris#71]
This just started happening and was passing before with the exact same code. I think it's reaching out to talk to an external service?

> 1) filter_wiris_filter_performance_svg_testcase::test_filter_safexml_with_performance_svg
> Failed asserting that false is true.
> 
> /var/www/site/filter/wiris/tests/filter_performance_svg_test.php:84
> /var/www/site/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
>  vendor/bin/phpunit "filter_wiris_filter_performance_svg_testcase" filter/wiris/tests/filter_performance_svg_test.php

**Comment by dcanetma** [comment]
Hola, Kristina

In order to render the the mathematical formulas to svg an external endpoint is using. Since this filter acts as a client API to the WIRIS render services.

**Comment by kristian-94** [comment]
@dcanetma  Do you know if the endpoint is working or is it down? How do I get this unit test to pass? Does it pass for you?

**Comment by dcanetma** [comment]
Yes, they do.

I've just checked locally, in order to be sure, and everything works as expected.

I'm sharing the log:

```sh
bin/moodle-docker-compose exec -T webserver vendor/bin/phpunit filter/wiris/tests/filter_performance_svg_test.php
Moodle 3.9.1+ (Build: 20200827), b3b04e083bceb9ef999b01d1f8e97adf69dc52a9
Php: 7.4.8, mysqli: 5.7.27, OS: Linux 5.4.0-48-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

......                                                              6 / 6 (100%)

Time: 4.82 seconds, Memory: 38.00 MB

OK (6 tests, 6 assertions)
```

At the same time, all tests pass when they [are executed on the Travis CI pipeline](https://travis-ci.org/github/wiris/moodle-filter_wiris/builds/727703846).

**Comment by kristian-94** [comment]
Thank you for that, I'll have to look into it more :+1:
