### ISSUE TITLE
After upgrade to 7.23 I am getting a lot of web request to filter/wiris/integration/configurationjs.php

### ISSUE THREAD

**Issue by nadavkav** [wiris/moodle-filter_wiris#72]
It seems I am getting weird and maybe redundant web requests to filter/wiris/integration/configurationjs.php as I open a question for editing.

![image](https://user-images.githubusercontent.com/231168/95782476-a07dcb80-0cd8-11eb-9ce9-365d54f014ac.png)

What do you think?

**Comment by dcanetma** [comment]
Hola, @nadavkav 

Thanks for reporting the issue.

We'll try to reproduce and fix it.

Keep you posted.

**Comment by dcanetma** [comment]
Hola, @nadavkav 

I've not been able to reproduce the issue. Everything seems to work fine. 

To validate it I've tried to add a mathematical formula to a question on both 7.21 and 7.24 versions of this plugin. 

The result was as expected: there were as many requests to '/filter/wiris/integration/configurationjs.php' as Atto editor's instances on the page. 

Therefore, could you have a look to the intructions below and try to provide more context?

I've included a video validating the process, on before and after the update, to document it.

### Provide detailed reproduction steps (if any) 

1. Configure a moodle instance using filter "moodle-filter_wiris" on 7.21 release version.
2. Edit a Question on a quiz.
3. Open web inspector, go to the network tab and filter resources by 'config' word. 
4. Add a mathematical formula using MathType editor.
5. Insert the formula to the editor's target.
6. Save and keep on the same page.
7. Refresh the page and check how many calls to the '/filter/wiris/integration/configurationjs.php' URL are made. ( See [video](https://drive.google.com/file/d/1u4HK_t5dglfmCR_GUob_qpTMTelJOzyR/view?usp=sharing) )
8. Update "moodle-filter_wiris" to 7.24 release
9. Perform database upgrade
10. Repeat steps from 2 to 7. ( See [video](https://drive.google.com/file/d/1XyZVvo-CzE_CLhGVz5Qf0e7W9NHjcVhg/view?usp=sharing) )

### Expected result

The browser makes as many calls to the MathType configuration API endpoint accessing '/filter/wiris/integration/configurationjs.php' as editor's instances on the page.

### Actual result

The actual result is the expected result. No issues detected.

**Comment by nadavkav** [comment]
Thank you @dcanetma for the detailed check! it help me figure out this issue,
which is not an issue after all :smile: 

Our teachers use Formulas question type, with 10 parts, and in each part has 6 ATTO instances (1 for the answer and another 5 for the different feedbacks) which are all hidden under "More options...", that I missed (me bad).
Now, if you do you math... there are a lot of ATTO editors on that page.
Which explains the long list of WIRIS API calls to configurationjs.php

I wonder if there is a way to optimize those API calls, as they are all the same.
Maybe cache it in the browser's localcache ?
What do you think?

**Comment by dcanetma** [comment]
You're welcome, @nadavkav 

If this is the case, and you agree, I'm closing the issue, then.

About the calls to the configuration file for each editor's instance, it has some drawbacks and should be studied in its context.

Many thanks for reporting the issue!
