### ISSUE TITLE
Script source issue

### ISSUE THREAD

**Issue by SvilenStoianov** [wiris/moodle-filter_wiris#75]
Hello. Using Moodle 3.9 and Wiris Filter 7.24. Until yesterday, everything was fine. No change was maded and today equation editor is not loading. In console I've noticed that:
```

15:24:05.530 GEThttps://www.wiris.net//demo/editor/editor?lang=en&stats-editor=unknown&stats-mode=safeXml&stats-version=7.23.0
[HTTP/2 403 Forbidden 716ms]
```

There is double slash after domain name. But in settings all is correct:
Service path is set to **/demo/editor/render**

I've tried to remove first slash in setting but that do not solve the issue.

Thank you.

**Comment by dcanetma** [comment]
Hola @SvilenStoianov,

Our fault. 
We had a temporary issue on our servers that may have cause the issue.

It's working by now.
You can contact us at team.support.europe@wiris.com if you ever found issues of the kind in the future.

Many thanks for reporting the issue.

Kind regards.
