### ISSUE TITLE
Not Install plugins in PHP 8.0

### ISSUE THREAD

**Issue by hongm32** [wiris/moodle-filter_wiris#83]
Install plugins in PHP 8.0.7
Press "Upgrade Moodle database now" shows:

uncaught exception: Too few arguments to function _hx_error_handler(), 4 passed and exactly 5 expected

in file: /www/moodle/filter/wiris/integration/lib/php/Boot.class.php line 253
#0 [internal function]: _hx_error_handler()
#1 /www/moodle/filter/wiris/integration/lib/php/Boot.class.php(876): file_put_contents()
#2 /www/moodle/filter/wiris/integration/lib/com/wiris/system/CallWrapper.class.php(44): require_once('...')
#3 /www/moodle/filter/wiris/classes/pluginwrapper.php(80): com_wiris_system_CallWrapper->init()
#4 /www/moodle/filter/wiris/classes/pluginwrapper.php(54): filter_wiris_pluginwrapper->init()
#5 /www/moodle/filter/wiris/settings.php(35): filter_wiris_pluginwrapper->__construct()
#6 /www/moodle/lib/classes/plugininfo/filter.php(88): include('...')
#7 /www/moodle/admin/settings/plugins.php(245): core\plugininfo\filter->load_settings()
#8 /www/moodle/lib/adminlib.php(8842): require('...')
#9 /www/moodle/admin/upgradesettings.php(22): admin_get_root()
#10 {main}

**Comment by dcanet-at-wiris** [comment]
Thanks for reporting.
The development of the PHP8 support is still on development.
