### ISSUE TITLE
Deprecated property configurationService. Use serviceParameters on instead.

### ISSUE THREAD

**Issue by nadavkav** [wiris/moodle-filter_wiris#85]
I am getting a lot of console messages like:
"Deprecated property configurationService. Use serviceParameters on instead."
Is that OK?

All seems to work fine, weird.

**Comment by dcanet-at-wiris** [comment]
Thanks for reaching us, @nadavkav 

Yes, it's normal.

It's a warning message from the API service and the plugin prints it out in console as a result.

I agree with you that it's not very elegant. We're planning to solve it on a further release of the filter to fix this message for good.

Kind regards,

D.
