### ISSUE TITLE
Manage MathType Web Integration configuration data dinamically using Moodle's Admin settings UI

### ISSUE THREAD

**Issue by dcanet-at-wiris** [wiris/moodle-filter_wiris#91]
## Manage MathType Web Integration configuration data dinamically using Moodle's Admin settings UI

We want to allow users to manage the MathType Web Integration configuration settings data dinamically using Moodle's Admin settings UI and store them using a Moodle's complaing solution.

We've defined these next user stories:

**01: Manage settings dinamically**

> As a Moodle Administrator,  
> I want to manage the configuration settings from the MathType Web Integration library,
> that is a third-party dependency of the plugin, 
> using the regular Moodle's Admin UI,
> so I don't need to manage them using a static file on the plugin's root folder. 

**02: Upgrading the plugin**

> As a Moodle Administrator
> when upgrading to the latest version of this plugin,
> of an instance using the `filter/wiris/configuration.ini` file method,  
> I want an automatic upgrade path to keep things consistent, and
> be informed of any important information.

## Issue definition

This plugin stores some of its configuration's settings data in the plugin's root folder, using a static file named  [configuration.ini.dist](../configuration.ini.dist).

The [configuration.ini.dist](../configuration.ini.dist) is part of the "MathType Web Integration PHP" library filter that allows Moodle to access the render services provided by the Wiris API.

> For more details, visit [MathType Configuration table docs page][doc-config] and [thirdpartylibs.xml](thirdpartylibs.xml).

### Analysis

Using a static file to store configuration's settings data is bad since:

* It may lead to problems and additional steps during deployment of new plugin versions or to possibly ignoring the configuration because of the unusual storing point.
* The configuration file can be potentially be removed when upgrading this plugin's code on the Moodle instance.
* It's not a Moodle plugin development good practice.

### Motivation

The reasons to keep this file on the Moodle's root folder are:

- Compatibility with other PHP platforms where the MathType Web Integrations PHP library is used.
- Software maintanability: [the same strategy is used for other back-end platforms like .Net, Java or Rails][doc-config].
- Historical reasons: this library is being used for more than a decade now, so any solution we may come with should aim for complete backward compatibility.  
- Therefore, It would require a new feature request to specify which problem needs to be solved and a proposed solution.

## Feature request specification

We want to expose this configuration settings using Moodle's Admin settings UI and store them on a more Moodle's native way like [`config_plugins` tables](https://docs.moodle.org/dev/Admin_settings) or the [Moodledata directory](https://docs.moodle.org/22/en/Moodledata_directory).

In other words, the plugin's configuration settings data should be stored dinamically.

The plugin will expose "MathType Web Integration PHP" library configuration settings using Moodle's Admin settings UI, instead of the [configuration.ini.dist](../configuration.ini.dist) configuration file.

Admin users will be able to manage the MathType Web Integration Library Server configuration file (configuration.ini) settings using Moodle's UI.

The configuration settings data will be stored using Moodle plugins development best practices. Like [`config_plugins` tables](https://docs.moodle.org/dev/Admin_settings), the [Moodledata directory](https://docs.moodle.org/22/en/Moodledata_directory).

At the same time, we want to offer backward compatibility with Moodle installations using the current [configuration.ini.dist](../configuration.ini.dist) method.

Therefore, the solution proposed must also include an upgrade path when updating to this version of the plugin. 

So it would need to be decided what to do if the  [/configuration.ini.dist](/configuration.ini.dist) file already exists on a Moodle's instance. 

## Other details

* The original motivation of this feature request is @danowar2k 's reported issue: #79.

[doc-config]:https://docs.wiris.com/en/mathtype/mathtype_web/integrations/config-table#server_configuration_file_configurationini

**Comment by danowar2k** [comment]
This issue was marked as "completed". But is it really completed or rather "won't do"? I still see the configuration.ini.dist in the root code dir....
